Fix to PSR-4
php-slack/slack pull request #62
Opened 2021-03-04 04:08 UTC by yuuan

Fix these.

```
Class Slack\Tests\BlockElement\TextInputUnitTest located in ./vendor/alek13/slack/tests/BlockElement/TextInputTestCase.php does not comply with psr-4 autoloading standard. Skipping.
Class Slack\Tests\BlockElements\TextUnitTest located in ./vendor/alek13/slack/tests/BlockElement/TextUnitTest.php does not comply with psr-4 autoloading standard. Skipping.
```

These warnings are printed when composer install.

2021-03-05 23:24 UTC, cmbuckley requested changes
I think `TextInputTestCase.php` is the correct filename, and the class should be renamed to `Slack\Tests\BlockElement\TextInputTestCase`, rather than the other way around.

2021-03-05 23:26 UTC, cmbuckley approved these changes

2021-03-05 23:29 UTC, merged

2021-06-04 10:53 UTC, yuuan commented
Please publish a new version.

2021-06-09 21:59 UTC, alek13 commented
done